build(component-angular): fix jest output issue
It appears that the `build:test-results` command is being triggered before `build:components`,
causing an issue because the test command did not generate the `/dist` folder.

error message:

```
Error: ENOENT: no such file or directory, open 'path/utrecht/packages/component-library-angular/dist/.jest-test-results.json'
     at Object.openSync (node:fs:581:18)
     at Object.writeFileSync (node:fs:2342:35) 
```